groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  # - load-tests
  - promote-new-version

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/pivotalservices/concourse-pipeline-samples.git
- name: PAS
  type: cf
  source:
    api: {{pas-api}}
    organization: {{pas-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pas-space}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PAS_APP_SUFFIX: {{pas-app-suffix}}
      PAS_API: {{pas-api}}
      PAS_ORG: {{pas-organization}}
      PAS_USER: {{deploy-username}}
      PAS_PWD: {{deploy-password}}
      PAS_SPACE: {{pas-space}}
  - task: prepare-app-manifest
    file: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/app-manifest-prep.yml
    params:
      PAS_APP_SUFFIX: {{pas-app-suffix}}
  - put: PAS
    params:
      manifest: app-manifest-output/manifest.yml
      path: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/bgd-app

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    # passed:
    #   - load-tests
  - task: get-current-app-color
    file: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PAS_APP_SUFFIX: {{pas-app-suffix}}
      PAS_API: {{pas-api}}
      PAS_ORG: {{pas-organization}}
      PAS_USER: {{deploy-username}}
      PAS_PWD: {{deploy-password}}
      PAS_SPACE: {{pas-space}}
  - task: switch-app-routes
    file: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/update-routes.yml
    params:
      PAS_APP_SUFFIX: {{pas-app-suffix}}
      PAS_APP_DOMAIN: {{pas-app-domain}}
      PAS_API: {{pas-api}}
      PAS_ORG: {{pas-organization}}
      PAS_USER: {{deploy-username}}
      PAS_PWD: {{deploy-password}}
      PAS_SPACE: {{pas-space}}
